### ISSUE TITLE
感觉过滤域名有点离谱……

### ISSUE THREAD

**Issue by hjthjthjt** [eallion/uBlacklist-subscription-compilation#1]
居然还有过滤京东的……
![image](https://user-images.githubusercontent.com/3889846/96203562-ccc57080-0f94-11eb-99cf-ad1cf620e69e.png)

你说过滤 CSDN 是一回事，毕竟确实有不少复制粘贴，但是也有不少是真的有用的

啊我知道是收集的，不知道是你哪个源屏蔽的

**Comment by eallion** [comment]
这个情况我知道的，不过我还在用，也没有管，因为插件支持随时显示所有搜索结果。

![2020-12-22_22-50](https://user-images.githubusercontent.com/1698841/102901069-2328c100-44a8-11eb-93f8-fdc4092f36c6.png)

不过我个人觉得，在 Google 的结果中显示京东的结果，反而更应该屏蔽。

**Comment by eallion** [comment]
最离谱的一次是，有一个上游的列表屏蔽了中文维基百科的结果，我只修改过这一次。

不过总体来说，这个列表确实很激进，但个人觉得很好用。

**Comment by cielpy** [comment]
有点过于激进了

@*://post.smzdm.com/*
@*://zhuanlan.zhihu.com/*
@*://www.zhihu.com/*
@*://www.jianshu.com/*
@*://www.sohu.com/*
@*://my.oschina.net/*
@*://new.qq.com/*

这些网站我觉得不能算是垃圾站吧，顶多就是质量不是很高，但是还是很多原创内容的，没有屏蔽的必要我觉得

然后今天发现把 medium 屏蔽了。。。我是不敢用了，查了一下都是来源于 https://github.com/yangjingchuang/ublacklist-subscription 这个仓库

建议去掉 https://github.com/yangjingchuang/ublacklist-subscription 吧

我在自己的 fork 去掉了，自己先用着了

**Comment by eallion** [comment]
@cielpy 好，我把这个去掉。

**Comment by cielpy** [comment]
那我提个 PR 吧

**Comment by eallion** [comment]
我已经改了。

不过屏蔽知乎的有好几个源。

**Comment by cielpy** [comment]
不是很离谱的话自己点一下不屏蔽就可以了，还好

**Comment by cielpy** [comment]
实测了一下知乎不会被屏蔽
![image](https://user-images.githubusercontent.com/3138493/103088715-98220500-4626-11eb-9155-bdbf1a8ca0f1.png)

@开头的是不屏蔽，不过在@之前的是屏蔽规则吧，前面的不会先命中吗

**Comment by eallion** [comment]
这是文档：
- 匹配模式：<https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Match_patterns>
- 正则表达式：<https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Regular_Expressions>

**Comment by eallion** [comment]
你可以更新列表后，用 `钢笔 site:zhihu.com`、`钢笔 site:item.jd.com`这样试。

**Comment by cielpy** [comment]
![image](https://user-images.githubusercontent.com/3138493/103089124-fc919400-4627-11eb-8592-7e032c7ab882.png)
![image](https://user-images.githubusercontent.com/3138493/103089135-04513880-4628-11eb-97e0-9c981d34dd4f.png)
不会屏蔽

**Comment by eallion** [comment]
`@` 在后面，后面的规则生效。

**Comment by teohhanhui** [comment]
https://github.com/nonPointer/uBlacklist-Subscription/blob/fdb27f781a1ad5a0937bc351e6b4e2abfdf5954a/blacklist.txt#L319

這個似乎也太離譜了 :sob:
