### ISSUE TITLE
过滤过于激进, Google被屏蔽

### ISSUE THREAD

**Issue by SunBK201** [eallion/uBlacklist-subscription-compilation#13]
<img width="763" alt="Xnip2022-01-28_20-39-01" src="https://user-images.githubusercontent.com/49178170/151548813-fb4ad8bf-db3f-41d1-8c65-8086911e6a21.png">
<img width="350" alt="Xnip2022-01-28_20-41-06" src="https://user-images.githubusercontent.com/49178170/151548821-135da0ac-48fd-4cb9-a1f1-4d04a0b2dba0.png">

**Comment by SunBK201** [comment]
来源: https://github.com/scyrte/uBlacklist-Subscription
https://github.com/scyrte/uBlacklist-Subscription/blob/d36f6e4d61fd0bda145970180e92ecb3b4b29d65/blacklist.txt#L92

**Comment by eallion** [comment]
这个确实想不到，但一般也不会用 google 搜 google 。年后处理。

**Comment by Butanediol** [comment]
> 这个确实想不到，但一般也不会用 google 搜 google 。年后处理。

关键是 Google 的其他业务也使用这个域名，而不是 x.google.com 之类的子域名。

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/22426749/153590306-a895e432-802c-42cd-968c-41ab75853b71.png">
