### ISSUE TITLE
请求鉴别

### ISSUE THREAD

**Issue by InPRTx** [eallion/uBlacklist-subscription-compilation#31]
https://www.zkxjob.com/
看[关于页](https://www.zkxjob.com/8787)，感觉可能还像模像样的
在[这篇文章内](https://www.zkxjob.com/27262) 出现了，点击上方**学python，
感觉应该可能是搬运的
最后的话，2325篇文章，emmmm

![image](https://user-images.githubusercontent.com/56180468/170736971-ffd0bc80-83f6-4f11-a3e7-a4749bb78971.png)

**Comment by eallion** [comment]
可能是个采集网。这种自己加入黑名单就可以的。

**Comment by InPRTx** [comment]
所以，这种网站符合你的屏蔽规则？

**Comment by eallion** [comment]
这个仓库本身是没有自己的规则的，都是合并上游的其他规则，做了一个合集。

**Comment by InPRTx** [comment]
#33
