### ISSUE TITLE
Reverse URL to unblock

### ISSUE THREAD

**Issue by eallion** [eallion/uBlacklist-subscription-compilation#5]
需要解除屏蔽的域名：（前面加`@`）
```
@*://www.baidu.com/*
```

Edit：需要添加域名可直接发新的 Issue。 [![](https://img.shields.io/badge/-New%20issue-2da44e)](https://github.com/eallion/uBlacklist-subscription-compilation/issues/new)

**Comment by lixiangyang9b** [comment]
@*://*.blog.csdn.net/*
