### ISSUE TITLE
Why we block openai.com?

### ISSUE THREAD

**Issue by laipz8200** [eallion/uBlacklist-subscription-compilation#52]
Hello, I found OpenAI's sites are blocked, but why?

https://github.com/eallion/uBlacklist-subscription-compilation/blob/187563eea21ed4bc99b9e2806ecaf74fdac00917/uBlacklist.txt#L7326

**Comment by eallion** [comment]
Blocked by https://github.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist

**Comment by laipz8200** [comment]
Got it, thank you.
