### ISSUE TITLE
https://www.youtube.com/watch?v=iBLn3qQyBSw被屏蔽

### ISSUE THREAD

**Issue by hsingll** [eallion/uBlacklist-subscription-compilation#53]
我搜索发现这个结果被屏蔽了（谷歌搜索`安卓 类似星露谷物语`），应该是一个误报，我不太懂正则，只能通过勾选订阅确定是这个合集屏蔽的，并不能分析出是哪条规则命中的

**Comment by eallion** [comment]
被 https://github.com/nonPointer/uBlacklist-Subscription 屏蔽
```
title/.*\- app下载(手机|可?提现|安卓|android)版.*/
```
